server:
  port: 8081
  servlet.context-path: /multitenant-plus
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mybatis_plus
    username: root
    password: 123456@A
  jpa:
    show-sql: true